---

- name: Install Redis
  dnf: name={{ item }} state=present
  with_items:
    - python-redis
    - python-trollius
    - redis


- name: Start Redis
  service: name=redis state=started enabled=yes
