---

- name: Install Pagure milter packages
  dnf: name={{ item }} state=present enablerepo=updates-testing
  with_items:
    - postfix
    - python3-pymilter

- name: Start Postfix
  service: name=postfix state=started enabled=yes
